/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

public class Assignment7Test {
    Set<Integer> treeSet, hashSet;
    Comparator<Integer> comp;

    @Before
    public void beforeEachTest() {
        comp = (o1, o2) -> Math.abs(o1) - Math.abs(o2);
               
        treeSet = new TreeSet<String>();
        hashSet = new HashSet<String>();

        treeSet.add("antelope");
        treeSet.add("dog");
        treeSet.add("cat");

    }

    @Test
    public void testEqualityOfSets() {
        assertNotEquals(treeSet, hashSet);
        System.out.println("TreeSet is "+treeSet);
        System.out.println("HashSet is "+hashSet);
    }

    @Test
    public void testViolationOfContract() {
        Integer a = 3;
        Integer b = -3;
        assertEquals(0, comp.compare(a, b));
        assertFalse(a.equals(b));
        System.out.println("comp.compare(a,b) = "+comp.compare(a, b));
        System.out.println("a.equals(b) = "+a.equals(b));

    }

    @Test(expected = NullPointerException.class)
    public void testNPE(){
        Integer a = null;
        Integer b = 3;
        comp.compare(a, b);
    }
}
